Algoritmo "pares_consecutivos"

Var
numero, soma, x : inteiro


Inicio
escreva("Digite um numero inteiro: ")
leia(numero)

enquanto numero <> 0 faca
         if numero % 2 <> 0 entao
            numero <- numero + 1
         fimse

         soma <- <- 5 * X + 20
         escreval("SOMA = ", soma)

         escreva("Digite um numero inteiro: ")
         leia(numero)
fimenquanto



Fimalgoritmo